//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AssetBuilder.Data {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DataSoap", Namespace="http://tempuri.org/")]
    public partial class Data : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback OptumGetUmichDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback getHealthAssessmentDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback PathwaysGetSnapshotOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSnapshotOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateSnapshotOperationCompleted;
        
        private System.Threading.SendOrPostCallback HealthgradesGetSnapshotOperationCompleted;
        
        private System.Threading.SendOrPostCallback getLanguageOperationCompleted;
        
        private System.Threading.SendOrPostCallback setLanguageOperationCompleted;
        
        private System.Threading.SendOrPostCallback searchLanguageOperationCompleted;
        
        private System.Threading.SendOrPostCallback OptumGetSnapshotOperationCompleted;
        
        private System.Threading.SendOrPostCallback OptumSaveSnapshotOperationCompleted;
        
        private System.Threading.SendOrPostCallback OptumPushToEHPOperationCompleted;
        
        private System.Threading.SendOrPostCallback OptumPrepopHistoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback validateContentOperationCompleted;
        
        private System.Threading.SendOrPostCallback processQuestionOperationCompleted;
        
        private System.Threading.SendOrPostCallback getQuestionStringOperationCompleted;
        
        private System.Threading.SendOrPostCallback DevGetValueOperationCompleted;
        
        private System.Threading.SendOrPostCallback DevGenderTextOperationCompleted;
        
        private System.Threading.SendOrPostCallback DevTestEvalOperationCompleted;
        
        private System.Threading.SendOrPostCallback DevGetInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback PublishOperationCompleted;
        
        private System.Threading.SendOrPostCallback exportAlgoOperationCompleted;
        
        private System.Threading.SendOrPostCallback generateSQLOperationCompleted;
        
        private System.Threading.SendOrPostCallback OptumGetSF12ScoreOperationCompleted;
        
        private System.Threading.SendOrPostCallback TableUpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback getQuestionOperationCompleted;
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Data() {
            this.Url = global::AssetBuilder.Properties.Settings.Default.AssetBuilder_Data_Data;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event OptumGetUmichDataCompletedEventHandler OptumGetUmichDataCompleted;
        
        /// <remarks/>
        public event getHealthAssessmentDataCompletedEventHandler getHealthAssessmentDataCompleted;
        
        /// <remarks/>
        public event PathwaysGetSnapshotCompletedEventHandler PathwaysGetSnapshotCompleted;
        
        /// <remarks/>
        public event GetSnapshotCompletedEventHandler GetSnapshotCompleted;
        
        /// <remarks/>
        public event CreateSnapshotCompletedEventHandler CreateSnapshotCompleted;
        
        /// <remarks/>
        public event HealthgradesGetSnapshotCompletedEventHandler HealthgradesGetSnapshotCompleted;
        
        /// <remarks/>
        public event getLanguageCompletedEventHandler getLanguageCompleted;
        
        /// <remarks/>
        public event setLanguageCompletedEventHandler setLanguageCompleted;
        
        /// <remarks/>
        public event searchLanguageCompletedEventHandler searchLanguageCompleted;
        
        /// <remarks/>
        public event OptumGetSnapshotCompletedEventHandler OptumGetSnapshotCompleted;
        
        /// <remarks/>
        public event OptumSaveSnapshotCompletedEventHandler OptumSaveSnapshotCompleted;
        
        /// <remarks/>
        public event OptumPushToEHPCompletedEventHandler OptumPushToEHPCompleted;
        
        /// <remarks/>
        public event OptumPrepopHistoryCompletedEventHandler OptumPrepopHistoryCompleted;
        
        /// <remarks/>
        public event validateContentCompletedEventHandler validateContentCompleted;
        
        /// <remarks/>
        public event processQuestionCompletedEventHandler processQuestionCompleted;
        
        /// <remarks/>
        public event getQuestionStringCompletedEventHandler getQuestionStringCompleted;
        
        /// <remarks/>
        public event DevGetValueCompletedEventHandler DevGetValueCompleted;
        
        /// <remarks/>
        public event DevGenderTextCompletedEventHandler DevGenderTextCompleted;
        
        /// <remarks/>
        public event DevTestEvalCompletedEventHandler DevTestEvalCompleted;
        
        /// <remarks/>
        public event DevGetInfoCompletedEventHandler DevGetInfoCompleted;
        
        /// <remarks/>
        public event PublishCompletedEventHandler PublishCompleted;
        
        /// <remarks/>
        public event exportAlgoCompletedEventHandler exportAlgoCompleted;
        
        /// <remarks/>
        public event generateSQLCompletedEventHandler generateSQLCompleted;
        
        /// <remarks/>
        public event OptumGetSF12ScoreCompletedEventHandler OptumGetSF12ScoreCompleted;
        
        /// <remarks/>
        public event TableUpdateCompletedEventHandler TableUpdateCompleted;
        
        /// <remarks/>
        public event getDataCompletedEventHandler getDataCompleted;
        
        /// <remarks/>
        public event getQuestionCompletedEventHandler getQuestionCompleted;
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OptumGetUmichData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode OptumGetUmichData(string TraversalID) {
            object[] results = this.Invoke("OptumGetUmichData", new object[] {
                        TraversalID});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void OptumGetUmichDataAsync(string TraversalID) {
            this.OptumGetUmichDataAsync(TraversalID, null);
        }
        
        /// <remarks/>
        public void OptumGetUmichDataAsync(string TraversalID, object userState) {
            if ((this.OptumGetUmichDataOperationCompleted == null)) {
                this.OptumGetUmichDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOptumGetUmichDataOperationCompleted);
            }
            this.InvokeAsync("OptumGetUmichData", new object[] {
                        TraversalID}, this.OptumGetUmichDataOperationCompleted, userState);
        }
        
        private void OnOptumGetUmichDataOperationCompleted(object arg) {
            if ((this.OptumGetUmichDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OptumGetUmichDataCompleted(this, new OptumGetUmichDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getHealthAssessmentData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode getHealthAssessmentData(string TraversalID, int RiskForAge, int[] Conclusions) {
            object[] results = this.Invoke("getHealthAssessmentData", new object[] {
                        TraversalID,
                        RiskForAge,
                        Conclusions});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void getHealthAssessmentDataAsync(string TraversalID, int RiskForAge, int[] Conclusions) {
            this.getHealthAssessmentDataAsync(TraversalID, RiskForAge, Conclusions, null);
        }
        
        /// <remarks/>
        public void getHealthAssessmentDataAsync(string TraversalID, int RiskForAge, int[] Conclusions, object userState) {
            if ((this.getHealthAssessmentDataOperationCompleted == null)) {
                this.getHealthAssessmentDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetHealthAssessmentDataOperationCompleted);
            }
            this.InvokeAsync("getHealthAssessmentData", new object[] {
                        TraversalID,
                        RiskForAge,
                        Conclusions}, this.getHealthAssessmentDataOperationCompleted, userState);
        }
        
        private void OngetHealthAssessmentDataOperationCompleted(object arg) {
            if ((this.getHealthAssessmentDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getHealthAssessmentDataCompleted(this, new getHealthAssessmentDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PathwaysGetSnapshot", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode PathwaysGetSnapshot(int CallID) {
            object[] results = this.Invoke("PathwaysGetSnapshot", new object[] {
                        CallID});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void PathwaysGetSnapshotAsync(int CallID) {
            this.PathwaysGetSnapshotAsync(CallID, null);
        }
        
        /// <remarks/>
        public void PathwaysGetSnapshotAsync(int CallID, object userState) {
            if ((this.PathwaysGetSnapshotOperationCompleted == null)) {
                this.PathwaysGetSnapshotOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPathwaysGetSnapshotOperationCompleted);
            }
            this.InvokeAsync("PathwaysGetSnapshot", new object[] {
                        CallID}, this.PathwaysGetSnapshotOperationCompleted, userState);
        }
        
        private void OnPathwaysGetSnapshotOperationCompleted(object arg) {
            if ((this.PathwaysGetSnapshotCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PathwaysGetSnapshotCompleted(this, new PathwaysGetSnapshotCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSnapshot", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetSnapshot(int CallID) {
            object[] results = this.Invoke("GetSnapshot", new object[] {
                        CallID});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetSnapshotAsync(int CallID) {
            this.GetSnapshotAsync(CallID, null);
        }
        
        /// <remarks/>
        public void GetSnapshotAsync(int CallID, object userState) {
            if ((this.GetSnapshotOperationCompleted == null)) {
                this.GetSnapshotOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSnapshotOperationCompleted);
            }
            this.InvokeAsync("GetSnapshot", new object[] {
                        CallID}, this.GetSnapshotOperationCompleted, userState);
        }
        
        private void OnGetSnapshotOperationCompleted(object arg) {
            if ((this.GetSnapshotCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSnapshotCompleted(this, new GetSnapshotCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateSnapshot", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateSnapshot(int CallID) {
            object[] results = this.Invoke("CreateSnapshot", new object[] {
                        CallID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateSnapshotAsync(int CallID) {
            this.CreateSnapshotAsync(CallID, null);
        }
        
        /// <remarks/>
        public void CreateSnapshotAsync(int CallID, object userState) {
            if ((this.CreateSnapshotOperationCompleted == null)) {
                this.CreateSnapshotOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateSnapshotOperationCompleted);
            }
            this.InvokeAsync("CreateSnapshot", new object[] {
                        CallID}, this.CreateSnapshotOperationCompleted, userState);
        }
        
        private void OnCreateSnapshotOperationCompleted(object arg) {
            if ((this.CreateSnapshotCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateSnapshotCompleted(this, new CreateSnapshotCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HealthgradesGetSnapshot", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode HealthgradesGetSnapshot(string TraversalID) {
            object[] results = this.Invoke("HealthgradesGetSnapshot", new object[] {
                        TraversalID});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void HealthgradesGetSnapshotAsync(string TraversalID) {
            this.HealthgradesGetSnapshotAsync(TraversalID, null);
        }
        
        /// <remarks/>
        public void HealthgradesGetSnapshotAsync(string TraversalID, object userState) {
            if ((this.HealthgradesGetSnapshotOperationCompleted == null)) {
                this.HealthgradesGetSnapshotOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHealthgradesGetSnapshotOperationCompleted);
            }
            this.InvokeAsync("HealthgradesGetSnapshot", new object[] {
                        TraversalID}, this.HealthgradesGetSnapshotOperationCompleted, userState);
        }
        
        private void OnHealthgradesGetSnapshotOperationCompleted(object arg) {
            if ((this.HealthgradesGetSnapshotCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HealthgradesGetSnapshotCompleted(this, new HealthgradesGetSnapshotCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getLanguage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode getLanguage(int AssetType, string AssetID, string Language) {
            object[] results = this.Invoke("getLanguage", new object[] {
                        AssetType,
                        AssetID,
                        Language});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void getLanguageAsync(int AssetType, string AssetID, string Language) {
            this.getLanguageAsync(AssetType, AssetID, Language, null);
        }
        
        /// <remarks/>
        public void getLanguageAsync(int AssetType, string AssetID, string Language, object userState) {
            if ((this.getLanguageOperationCompleted == null)) {
                this.getLanguageOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLanguageOperationCompleted);
            }
            this.InvokeAsync("getLanguage", new object[] {
                        AssetType,
                        AssetID,
                        Language}, this.getLanguageOperationCompleted, userState);
        }
        
        private void OngetLanguageOperationCompleted(object arg) {
            if ((this.getLanguageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getLanguageCompleted(this, new getLanguageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/setLanguage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode setLanguage(int AssetType, string AssetID, string Language, System.Xml.XmlNode Content) {
            object[] results = this.Invoke("setLanguage", new object[] {
                        AssetType,
                        AssetID,
                        Language,
                        Content});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void setLanguageAsync(int AssetType, string AssetID, string Language, System.Xml.XmlNode Content) {
            this.setLanguageAsync(AssetType, AssetID, Language, Content, null);
        }
        
        /// <remarks/>
        public void setLanguageAsync(int AssetType, string AssetID, string Language, System.Xml.XmlNode Content, object userState) {
            if ((this.setLanguageOperationCompleted == null)) {
                this.setLanguageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetLanguageOperationCompleted);
            }
            this.InvokeAsync("setLanguage", new object[] {
                        AssetType,
                        AssetID,
                        Language,
                        Content}, this.setLanguageOperationCompleted, userState);
        }
        
        private void OnsetLanguageOperationCompleted(object arg) {
            if ((this.setLanguageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setLanguageCompleted(this, new setLanguageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/searchLanguage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode searchLanguage(int AssetType, int SearchType, string Language, string search) {
            object[] results = this.Invoke("searchLanguage", new object[] {
                        AssetType,
                        SearchType,
                        Language,
                        search});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void searchLanguageAsync(int AssetType, int SearchType, string Language, string search) {
            this.searchLanguageAsync(AssetType, SearchType, Language, search, null);
        }
        
        /// <remarks/>
        public void searchLanguageAsync(int AssetType, int SearchType, string Language, string search, object userState) {
            if ((this.searchLanguageOperationCompleted == null)) {
                this.searchLanguageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsearchLanguageOperationCompleted);
            }
            this.InvokeAsync("searchLanguage", new object[] {
                        AssetType,
                        SearchType,
                        Language,
                        search}, this.searchLanguageOperationCompleted, userState);
        }
        
        private void OnsearchLanguageOperationCompleted(object arg) {
            if ((this.searchLanguageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.searchLanguageCompleted(this, new searchLanguageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OptumGetSnapshot", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode OptumGetSnapshot(string TraversalID) {
            object[] results = this.Invoke("OptumGetSnapshot", new object[] {
                        TraversalID});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void OptumGetSnapshotAsync(string TraversalID) {
            this.OptumGetSnapshotAsync(TraversalID, null);
        }
        
        /// <remarks/>
        public void OptumGetSnapshotAsync(string TraversalID, object userState) {
            if ((this.OptumGetSnapshotOperationCompleted == null)) {
                this.OptumGetSnapshotOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOptumGetSnapshotOperationCompleted);
            }
            this.InvokeAsync("OptumGetSnapshot", new object[] {
                        TraversalID}, this.OptumGetSnapshotOperationCompleted, userState);
        }
        
        private void OnOptumGetSnapshotOperationCompleted(object arg) {
            if ((this.OptumGetSnapshotCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OptumGetSnapshotCompleted(this, new OptumGetSnapshotCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OptumSaveSnapshot", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OptumSaveSnapshot(string TraversalID) {
            object[] results = this.Invoke("OptumSaveSnapshot", new object[] {
                        TraversalID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OptumSaveSnapshotAsync(string TraversalID) {
            this.OptumSaveSnapshotAsync(TraversalID, null);
        }
        
        /// <remarks/>
        public void OptumSaveSnapshotAsync(string TraversalID, object userState) {
            if ((this.OptumSaveSnapshotOperationCompleted == null)) {
                this.OptumSaveSnapshotOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOptumSaveSnapshotOperationCompleted);
            }
            this.InvokeAsync("OptumSaveSnapshot", new object[] {
                        TraversalID}, this.OptumSaveSnapshotOperationCompleted, userState);
        }
        
        private void OnOptumSaveSnapshotOperationCompleted(object arg) {
            if ((this.OptumSaveSnapshotCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OptumSaveSnapshotCompleted(this, new OptumSaveSnapshotCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OptumPushToEHP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OptumPushToEHP(string TraversalID) {
            object[] results = this.Invoke("OptumPushToEHP", new object[] {
                        TraversalID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OptumPushToEHPAsync(string TraversalID) {
            this.OptumPushToEHPAsync(TraversalID, null);
        }
        
        /// <remarks/>
        public void OptumPushToEHPAsync(string TraversalID, object userState) {
            if ((this.OptumPushToEHPOperationCompleted == null)) {
                this.OptumPushToEHPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOptumPushToEHPOperationCompleted);
            }
            this.InvokeAsync("OptumPushToEHP", new object[] {
                        TraversalID}, this.OptumPushToEHPOperationCompleted, userState);
        }
        
        private void OnOptumPushToEHPOperationCompleted(object arg) {
            if ((this.OptumPushToEHPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OptumPushToEHPCompleted(this, new OptumPushToEHPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OptumPrepopHistory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OptumPrepopHistory(string post, int MemberID, string TraversalID) {
            object[] results = this.Invoke("OptumPrepopHistory", new object[] {
                        post,
                        MemberID,
                        TraversalID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OptumPrepopHistoryAsync(string post, int MemberID, string TraversalID) {
            this.OptumPrepopHistoryAsync(post, MemberID, TraversalID, null);
        }
        
        /// <remarks/>
        public void OptumPrepopHistoryAsync(string post, int MemberID, string TraversalID, object userState) {
            if ((this.OptumPrepopHistoryOperationCompleted == null)) {
                this.OptumPrepopHistoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOptumPrepopHistoryOperationCompleted);
            }
            this.InvokeAsync("OptumPrepopHistory", new object[] {
                        post,
                        MemberID,
                        TraversalID}, this.OptumPrepopHistoryOperationCompleted, userState);
        }
        
        private void OnOptumPrepopHistoryOperationCompleted(object arg) {
            if ((this.OptumPrepopHistoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OptumPrepopHistoryCompleted(this, new OptumPrepopHistoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/validateContent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode validateContent(string algos, string source) {
            object[] results = this.Invoke("validateContent", new object[] {
                        algos,
                        source});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void validateContentAsync(string algos, string source) {
            this.validateContentAsync(algos, source, null);
        }
        
        /// <remarks/>
        public void validateContentAsync(string algos, string source, object userState) {
            if ((this.validateContentOperationCompleted == null)) {
                this.validateContentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvalidateContentOperationCompleted);
            }
            this.InvokeAsync("validateContent", new object[] {
                        algos,
                        source}, this.validateContentOperationCompleted, userState);
        }
        
        private void OnvalidateContentOperationCompleted(object arg) {
            if ((this.validateContentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.validateContentCompleted(this, new validateContentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/processQuestion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode processQuestion(bool rerender, System.Xml.XmlNode currentNode, System.Xml.XmlNode Form, string TraversalID, int MemberID, int CallID, bool NonExclusiveTableNone, bool WriteProcessed) {
            object[] results = this.Invoke("processQuestion", new object[] {
                        rerender,
                        currentNode,
                        Form,
                        TraversalID,
                        MemberID,
                        CallID,
                        NonExclusiveTableNone,
                        WriteProcessed});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void processQuestionAsync(bool rerender, System.Xml.XmlNode currentNode, System.Xml.XmlNode Form, string TraversalID, int MemberID, int CallID, bool NonExclusiveTableNone, bool WriteProcessed) {
            this.processQuestionAsync(rerender, currentNode, Form, TraversalID, MemberID, CallID, NonExclusiveTableNone, WriteProcessed, null);
        }
        
        /// <remarks/>
        public void processQuestionAsync(bool rerender, System.Xml.XmlNode currentNode, System.Xml.XmlNode Form, string TraversalID, int MemberID, int CallID, bool NonExclusiveTableNone, bool WriteProcessed, object userState) {
            if ((this.processQuestionOperationCompleted == null)) {
                this.processQuestionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnprocessQuestionOperationCompleted);
            }
            this.InvokeAsync("processQuestion", new object[] {
                        rerender,
                        currentNode,
                        Form,
                        TraversalID,
                        MemberID,
                        CallID,
                        NonExclusiveTableNone,
                        WriteProcessed}, this.processQuestionOperationCompleted, userState);
        }
        
        private void OnprocessQuestionOperationCompleted(object arg) {
            if ((this.processQuestionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.processQuestionCompleted(this, new processQuestionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getQuestionString", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode getQuestionString(string question, int CallID, string TraversalID, int MemberID, int StartAlgoID, int StartNodeID, int Counter) {
            object[] results = this.Invoke("getQuestionString", new object[] {
                        question,
                        CallID,
                        TraversalID,
                        MemberID,
                        StartAlgoID,
                        StartNodeID,
                        Counter});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void getQuestionStringAsync(string question, int CallID, string TraversalID, int MemberID, int StartAlgoID, int StartNodeID, int Counter) {
            this.getQuestionStringAsync(question, CallID, TraversalID, MemberID, StartAlgoID, StartNodeID, Counter, null);
        }
        
        /// <remarks/>
        public void getQuestionStringAsync(string question, int CallID, string TraversalID, int MemberID, int StartAlgoID, int StartNodeID, int Counter, object userState) {
            if ((this.getQuestionStringOperationCompleted == null)) {
                this.getQuestionStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetQuestionStringOperationCompleted);
            }
            this.InvokeAsync("getQuestionString", new object[] {
                        question,
                        CallID,
                        TraversalID,
                        MemberID,
                        StartAlgoID,
                        StartNodeID,
                        Counter}, this.getQuestionStringOperationCompleted, userState);
        }
        
        private void OngetQuestionStringOperationCompleted(object arg) {
            if ((this.getQuestionStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getQuestionStringCompleted(this, new getQuestionStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DevGetValue", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DevGetValue(string TraversalID, int QuestionID, int AnswerID, string Value) {
            object[] results = this.Invoke("DevGetValue", new object[] {
                        TraversalID,
                        QuestionID,
                        AnswerID,
                        Value});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DevGetValueAsync(string TraversalID, int QuestionID, int AnswerID, string Value) {
            this.DevGetValueAsync(TraversalID, QuestionID, AnswerID, Value, null);
        }
        
        /// <remarks/>
        public void DevGetValueAsync(string TraversalID, int QuestionID, int AnswerID, string Value, object userState) {
            if ((this.DevGetValueOperationCompleted == null)) {
                this.DevGetValueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDevGetValueOperationCompleted);
            }
            this.InvokeAsync("DevGetValue", new object[] {
                        TraversalID,
                        QuestionID,
                        AnswerID,
                        Value}, this.DevGetValueOperationCompleted, userState);
        }
        
        private void OnDevGetValueOperationCompleted(object arg) {
            if ((this.DevGetValueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DevGetValueCompleted(this, new DevGetValueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DevGenderText", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DevGenderText(string s) {
            object[] results = this.Invoke("DevGenderText", new object[] {
                        s});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DevGenderTextAsync(string s) {
            this.DevGenderTextAsync(s, null);
        }
        
        /// <remarks/>
        public void DevGenderTextAsync(string s, object userState) {
            if ((this.DevGenderTextOperationCompleted == null)) {
                this.DevGenderTextOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDevGenderTextOperationCompleted);
            }
            this.InvokeAsync("DevGenderText", new object[] {
                        s}, this.DevGenderTextOperationCompleted, userState);
        }
        
        private void OnDevGenderTextOperationCompleted(object arg) {
            if ((this.DevGenderTextCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DevGenderTextCompleted(this, new DevGenderTextCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DevTestEval", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double DevTestEval(string s) {
            object[] results = this.Invoke("DevTestEval", new object[] {
                        s});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void DevTestEvalAsync(string s) {
            this.DevTestEvalAsync(s, null);
        }
        
        /// <remarks/>
        public void DevTestEvalAsync(string s, object userState) {
            if ((this.DevTestEvalOperationCompleted == null)) {
                this.DevTestEvalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDevTestEvalOperationCompleted);
            }
            this.InvokeAsync("DevTestEval", new object[] {
                        s}, this.DevTestEvalOperationCompleted, userState);
        }
        
        private void OnDevTestEvalOperationCompleted(object arg) {
            if ((this.DevTestEvalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DevTestEvalCompleted(this, new DevTestEvalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DevGetInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode DevGetInfo(string procedure) {
            object[] results = this.Invoke("DevGetInfo", new object[] {
                        procedure});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void DevGetInfoAsync(string procedure) {
            this.DevGetInfoAsync(procedure, null);
        }
        
        /// <remarks/>
        public void DevGetInfoAsync(string procedure, object userState) {
            if ((this.DevGetInfoOperationCompleted == null)) {
                this.DevGetInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDevGetInfoOperationCompleted);
            }
            this.InvokeAsync("DevGetInfo", new object[] {
                        procedure}, this.DevGetInfoOperationCompleted, userState);
        }
        
        private void OnDevGetInfoOperationCompleted(object arg) {
            if ((this.DevGetInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DevGetInfoCompleted(this, new DevGetInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Publish", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode Publish(int AlgoID, string User_Name, string source, string target) {
            object[] results = this.Invoke("Publish", new object[] {
                        AlgoID,
                        User_Name,
                        source,
                        target});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void PublishAsync(int AlgoID, string User_Name, string source, string target) {
            this.PublishAsync(AlgoID, User_Name, source, target, null);
        }
        
        /// <remarks/>
        public void PublishAsync(int AlgoID, string User_Name, string source, string target, object userState) {
            if ((this.PublishOperationCompleted == null)) {
                this.PublishOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPublishOperationCompleted);
            }
            this.InvokeAsync("Publish", new object[] {
                        AlgoID,
                        User_Name,
                        source,
                        target}, this.PublishOperationCompleted, userState);
        }
        
        private void OnPublishOperationCompleted(object arg) {
            if ((this.PublishCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PublishCompleted(this, new PublishCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/exportAlgo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string exportAlgo(string source, string target, string algos) {
            object[] results = this.Invoke("exportAlgo", new object[] {
                        source,
                        target,
                        algos});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void exportAlgoAsync(string source, string target, string algos) {
            this.exportAlgoAsync(source, target, algos, null);
        }
        
        /// <remarks/>
        public void exportAlgoAsync(string source, string target, string algos, object userState) {
            if ((this.exportAlgoOperationCompleted == null)) {
                this.exportAlgoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexportAlgoOperationCompleted);
            }
            this.InvokeAsync("exportAlgo", new object[] {
                        source,
                        target,
                        algos}, this.exportAlgoOperationCompleted, userState);
        }
        
        private void OnexportAlgoOperationCompleted(object arg) {
            if ((this.exportAlgoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.exportAlgoCompleted(this, new exportAlgoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/generateSQL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string generateSQL(string algos, bool loadalgo, string source) {
            object[] results = this.Invoke("generateSQL", new object[] {
                        algos,
                        loadalgo,
                        source});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void generateSQLAsync(string algos, bool loadalgo, string source) {
            this.generateSQLAsync(algos, loadalgo, source, null);
        }
        
        /// <remarks/>
        public void generateSQLAsync(string algos, bool loadalgo, string source, object userState) {
            if ((this.generateSQLOperationCompleted == null)) {
                this.generateSQLOperationCompleted = new System.Threading.SendOrPostCallback(this.OngenerateSQLOperationCompleted);
            }
            this.InvokeAsync("generateSQL", new object[] {
                        algos,
                        loadalgo,
                        source}, this.generateSQLOperationCompleted, userState);
        }
        
        private void OngenerateSQLOperationCompleted(object arg) {
            if ((this.generateSQLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.generateSQLCompleted(this, new generateSQLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OptumGetSF12Score", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode OptumGetSF12Score(string TraversalID) {
            object[] results = this.Invoke("OptumGetSF12Score", new object[] {
                        TraversalID});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void OptumGetSF12ScoreAsync(string TraversalID) {
            this.OptumGetSF12ScoreAsync(TraversalID, null);
        }
        
        /// <remarks/>
        public void OptumGetSF12ScoreAsync(string TraversalID, object userState) {
            if ((this.OptumGetSF12ScoreOperationCompleted == null)) {
                this.OptumGetSF12ScoreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOptumGetSF12ScoreOperationCompleted);
            }
            this.InvokeAsync("OptumGetSF12Score", new object[] {
                        TraversalID}, this.OptumGetSF12ScoreOperationCompleted, userState);
        }
        
        private void OnOptumGetSF12ScoreOperationCompleted(object arg) {
            if ((this.OptumGetSF12ScoreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OptumGetSF12ScoreCompleted(this, new OptumGetSF12ScoreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TableUpdate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode TableUpdate(string table, string data) {
            object[] results = this.Invoke("TableUpdate", new object[] {
                        table,
                        data});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void TableUpdateAsync(string table, string data) {
            this.TableUpdateAsync(table, data, null);
        }
        
        /// <remarks/>
        public void TableUpdateAsync(string table, string data, object userState) {
            if ((this.TableUpdateOperationCompleted == null)) {
                this.TableUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTableUpdateOperationCompleted);
            }
            this.InvokeAsync("TableUpdate", new object[] {
                        table,
                        data}, this.TableUpdateOperationCompleted, userState);
        }
        
        private void OnTableUpdateOperationCompleted(object arg) {
            if ((this.TableUpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TableUpdateCompleted(this, new TableUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode getData(string procedure, string[] args) {
            object[] results = this.Invoke("getData", new object[] {
                        procedure,
                        args});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void getDataAsync(string procedure, string[] args) {
            this.getDataAsync(procedure, args, null);
        }
        
        /// <remarks/>
        public void getDataAsync(string procedure, string[] args, object userState) {
            if ((this.getDataOperationCompleted == null)) {
                this.getDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDataOperationCompleted);
            }
            this.InvokeAsync("getData", new object[] {
                        procedure,
                        args}, this.getDataOperationCompleted, userState);
        }
        
        private void OngetDataOperationCompleted(object arg) {
            if ((this.getDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDataCompleted(this, new getDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getQuestion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode getQuestion(System.Xml.XmlNode question, int CallID, string TraversalID, int MemberID, int StartAlgoID, int StartNodeID, int Counter) {
            object[] results = this.Invoke("getQuestion", new object[] {
                        question,
                        CallID,
                        TraversalID,
                        MemberID,
                        StartAlgoID,
                        StartNodeID,
                        Counter});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void getQuestionAsync(System.Xml.XmlNode question, int CallID, string TraversalID, int MemberID, int StartAlgoID, int StartNodeID, int Counter) {
            this.getQuestionAsync(question, CallID, TraversalID, MemberID, StartAlgoID, StartNodeID, Counter, null);
        }
        
        /// <remarks/>
        public void getQuestionAsync(System.Xml.XmlNode question, int CallID, string TraversalID, int MemberID, int StartAlgoID, int StartNodeID, int Counter, object userState) {
            if ((this.getQuestionOperationCompleted == null)) {
                this.getQuestionOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetQuestionOperationCompleted);
            }
            this.InvokeAsync("getQuestion", new object[] {
                        question,
                        CallID,
                        TraversalID,
                        MemberID,
                        StartAlgoID,
                        StartNodeID,
                        Counter}, this.getQuestionOperationCompleted, userState);
        }
        
        private void OngetQuestionOperationCompleted(object arg) {
            if ((this.getQuestionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getQuestionCompleted(this, new getQuestionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public KeyValuePairOfStringObject[] HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((KeyValuePairOfStringObject[])(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KeyValuePairOfStringObject {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void OptumGetUmichDataCompletedEventHandler(object sender, OptumGetUmichDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OptumGetUmichDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OptumGetUmichDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getHealthAssessmentDataCompletedEventHandler(object sender, getHealthAssessmentDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getHealthAssessmentDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getHealthAssessmentDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void PathwaysGetSnapshotCompletedEventHandler(object sender, PathwaysGetSnapshotCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PathwaysGetSnapshotCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PathwaysGetSnapshotCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetSnapshotCompletedEventHandler(object sender, GetSnapshotCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSnapshotCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSnapshotCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CreateSnapshotCompletedEventHandler(object sender, CreateSnapshotCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateSnapshotCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateSnapshotCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void HealthgradesGetSnapshotCompletedEventHandler(object sender, HealthgradesGetSnapshotCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HealthgradesGetSnapshotCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HealthgradesGetSnapshotCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getLanguageCompletedEventHandler(object sender, getLanguageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getLanguageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getLanguageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void setLanguageCompletedEventHandler(object sender, setLanguageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setLanguageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setLanguageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void searchLanguageCompletedEventHandler(object sender, searchLanguageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class searchLanguageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal searchLanguageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void OptumGetSnapshotCompletedEventHandler(object sender, OptumGetSnapshotCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OptumGetSnapshotCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OptumGetSnapshotCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void OptumSaveSnapshotCompletedEventHandler(object sender, OptumSaveSnapshotCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OptumSaveSnapshotCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OptumSaveSnapshotCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void OptumPushToEHPCompletedEventHandler(object sender, OptumPushToEHPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OptumPushToEHPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OptumPushToEHPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void OptumPrepopHistoryCompletedEventHandler(object sender, OptumPrepopHistoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OptumPrepopHistoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OptumPrepopHistoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void validateContentCompletedEventHandler(object sender, validateContentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class validateContentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal validateContentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void processQuestionCompletedEventHandler(object sender, processQuestionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class processQuestionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal processQuestionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getQuestionStringCompletedEventHandler(object sender, getQuestionStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getQuestionStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getQuestionStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void DevGetValueCompletedEventHandler(object sender, DevGetValueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DevGetValueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DevGetValueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void DevGenderTextCompletedEventHandler(object sender, DevGenderTextCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DevGenderTextCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DevGenderTextCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void DevTestEvalCompletedEventHandler(object sender, DevTestEvalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DevTestEvalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DevTestEvalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void DevGetInfoCompletedEventHandler(object sender, DevGetInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DevGetInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DevGetInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void PublishCompletedEventHandler(object sender, PublishCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PublishCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PublishCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void exportAlgoCompletedEventHandler(object sender, exportAlgoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class exportAlgoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal exportAlgoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void generateSQLCompletedEventHandler(object sender, generateSQLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class generateSQLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal generateSQLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void OptumGetSF12ScoreCompletedEventHandler(object sender, OptumGetSF12ScoreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OptumGetSF12ScoreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OptumGetSF12ScoreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void TableUpdateCompletedEventHandler(object sender, TableUpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TableUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TableUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getDataCompletedEventHandler(object sender, getDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getQuestionCompletedEventHandler(object sender, getQuestionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getQuestionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getQuestionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public KeyValuePairOfStringObject[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((KeyValuePairOfStringObject[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591