# NOTE: Requires Windows Container
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8 AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY "src/WpfApplication1/*.csproj" .
RUN dotnet restore

# copy and build everything else
COPY ["src/WpfApplication1/*.csproj", "WpfApplication1/"]
COPY ["src/WpfApplication1/.", "./WpfApplication1/"]
#COPY ["src/Packages/.", "./Packages/"]
COPY ["src/ObjCompare/*.shproj", "ObjCompare/"]
COPY ["src/ObjCompare/.", "./ObjCompare/"]
WORKDIR /app
RUN dotnet publish -c Release -o out --no-restore


FROM mcr.microsoft.com/dotnet/framework/runtime:4.8 AS runtime
WORKDIR /app
COPY --from=build /app/out ./
ENTRYPOINT ["assetbuilder.exe"]